#!/bin/bash
# Build pkgcraft-c library for bundling with pkgcraft python wheels.

set -e
env

doecho() {
	echo "\$ $*"
	"$@"
}

# install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
doecho source "${HOME}"/.cargo/env

# install cargo-c via binary package
if [[ ${OSTYPE} == "linux-"* ]]; then
	curl -L https://github.com/lu-zero/cargo-c/releases/latest/download/cargo-c-linux.tar.gz | tar xvzf - -C "${HOME}"/.cargo/bin
elif [[ ${OSTYPE} == "darwin"* ]]; then
	curl -L https://github.com/lu-zero/cargo-c/releases/latest/download/cargo-c-macos.zip > cargo-c.zip
	unzip -o cargo-c.zip -d "${HOME}"/.cargo/bin
	rm cargo-c.zip
else
	echo "unknown OS: ${OSTYPE}"
	exit 1
fi

# install required clang libs on linux
if [[ ${OSTYPE} == "linux-gnu" ]]; then
	doecho dnf makecache --refresh
	doecho dnf -y install clang
elif [[ ${OSTYPE} == "linux-musl" ]]; then
	doecho apk update
	doecho apk add clang
fi

# update cargo lock file using dep versions from tagged releases
doecho cargo update
# build and install C library
doecho cargo cinstall -p pkgcraft-c
