#!/bin/bash
# Run pkgcraft tests in cibuildwheel.

set -e

PACKAGEDIR=$1
TESTDIR=$(mktemp -d)
pushd "${TESTDIR}" >/dev/null
tar -zxf "${PACKAGEDIR}"/dist/*.tar.gz --strip-components=1
PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest tests
popd >/dev/null
