#!/usr/bin/env python
# List all packages matching given restrictions.
#
# Example usage:
# - all pkgs with $PN starting in 'e'
#   query 'e*'
#
# - all non-gentoo repo pkgs:
#   query --restrict 'repo != "gentoo"'
#
# - maintainer-needed pkgs:
#   query --restrict 'maintainers is none'
#
# - pkgs maintained by three or more devs
#   query --restrict 'maintainers all (email=~"gentoo.org$" && type=="person") && maintainers >= 3'
#
# - pkgs implicitly using the flag-o-matic eclass:
#   query --restrict 'inherited >= {"flag-o-matic"} && !(inherit >= {"flag-o-matic"})'
#
# - dev-python/* pkgs with DEPEND=media-libs/* deps
#   query --restrict 'depend any "media-libs/*"' 'dev-python/*'

import argparse
from functools import reduce

from pkgcraft.config import Config
from pkgcraft.error import InvalidRestrict
from pkgcraft.restrict import Restrict


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--restrict', metavar='RESTRICT', dest='restricts', action='append')
    parser.add_argument('targets', metavar='TARGET', nargs='*')
    args = parser.parse_args()

    if not (args.restricts or args.targets):
        parser.error('restrictions and/or targets must be specified')

    def str_to_restrict(convert, combine, args):
        try:
            return reduce(combine, map(convert, args))
        except InvalidRestrict as e:
            parser.error(e)

    # convert strings to restrictions
    restricts = []
    if args.restricts:
        restricts.append(str_to_restrict(
            Restrict.pkg, lambda x, y: x & y, args.restricts))
    if args.targets:
        restricts.append(str_to_restrict(
            Restrict.dep, lambda x, y: x | y, args.targets))

    # combine pkg and target restrictions
    r = reduce(lambda x, y: x & y, restricts)

    config = Config(repos_conf=True)
    for pkg in config.repos.ebuild.iter_restrict(r):
        print(pkg)


if __name__ == '__main__':
    main()
