name: Deploy

on:
  push:
    branches: [deploy]
    tags: [v*]

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: 'x86_64'
          - os: ubuntu-latest
            arch: 'aarch64'
          - os: ubuntu-latest
            arch: 'ppc64le'
    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
      CIBW_CONTAINER_ENGINE: 'docker'
      CIBW_PLATFORM: 'auto'

    steps:
    - name: Checkout workspace
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft-workspace
        submodules: recursive
        # checkout full history to support tagged releases
        fetch-depth: 0

    - name: Pull submodule updates and checkout the latest tags if they exist
      run: |
        git submodule update --recursive --remote
        git submodule foreach 'git fetch origin; git checkout $(git describe --tags `git rev-list --tags --max-count=1`);'

    - name: Remove current repo from workspace
      run: rm -rfv ${{ github.event.repository.name }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # checkout full history for setuptools-scm
        fetch-depth: 0
        path: ${{ github.event.repository.name }}
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up QEMU
      if: runner.os == 'Linux' && matrix.arch != 'x86_64'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ matrix.arch }}

    - name: Build sdist and wheels
      run: ./build-wheels ${{ matrix.arch }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pkgcraft-python
        path: |
          pkgcraft-python/dist/
          pkgcraft-python/wheels/
        if-no-files-found: error
        retention-days: 1

    - name: Upload sdist to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: ${{ runner.os == 'Linux' && matrix.arch == 'x86_64' && startsWith(github.ref, 'refs/tags/') }}
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: pkgcraft-python/dist/

    - name: Upload wheels to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: pkgcraft-python/wheels/

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      if: ${{ runner.os == 'Linux' && matrix.arch == 'x86_64' && startsWith(github.ref, 'refs/tags/') }}
      with:
        files: pkgcraft-python/dist/*.tar.gz
        fail_on_unmatched_files: true
