name: Deploy

on:
  push:
    branches: [deploy]
    tags: [v*]

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # checkout full history for setuptools-scm
        fetch-depth: 0
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build sdist
      run: |
        pip install tox
        tox -e sdist

    - name: Upload sdist artifact
      uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: dist/*.tar.gz
        if-no-files-found: error
        retention-days: 3

  build-wheels:
    needs: ["build-sdist"]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: 'x86_64'
          - os: ubuntu-latest
            arch: 'aarch64'
          - os: ubuntu-latest
            arch: 'ppc64le'
    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
      CIBW_CONTAINER_ENGINE: 'docker'
      CIBW_PLATFORM: 'auto'

    steps:
    - name: Checkout workspace
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft-workspace
        submodules: recursive
        # checkout full history to support tagged releases
        fetch-depth: 0

    - name: Pull submodule updates and checkout the latest tags if they exist
      run: |
        git submodule update --recursive --remote
        git submodule foreach 'git fetch origin; git checkout $(git describe --tags `git rev-list --tags --max-count=1`);'

    - name: Remove current repo from workspace
      run: rm -rfv ${{ github.event.repository.name }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # checkout full history for setuptools-scm
        fetch-depth: 0
        path: ${{ github.event.repository.name }}
        submodules: recursive

    - name: Download sdist artifact
      uses: actions/download-artifact@v3
      with:
        name: sdist
        path: pkgcraft-python/dist

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up QEMU
      if: runner.os == 'Linux' && matrix.arch != 'x86_64'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ matrix.arch }}

    - name: Build wheels
      run: ./build-wheels ${{ matrix.arch }}

    - name: Verify wheels
      run: |
        pip install twine
        twine check pkgcraft-python/wheels/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: pkgcraft-python/wheels/
        if-no-files-found: error
        retention-days: 3

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: ["build-sdist", "build-wheels"]
    runs-on: ubuntu-latest
    steps:
    - name: Download sdist and wheel artifacts
      uses: actions/download-artifact@v3

    - name: Upload sdist to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: sdist/
        print_hash: true

    - name: Upload wheels to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: wheels/
        print_hash: true

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: sdist/*.tar.gz
        fail_on_unmatched_files: true
