name: Deploy

on:
  push:
    branches: [deploy]
    tags: [v*]

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.10'
          - os: macos-latest
            python-version: '3.10'
            macos_target: '10.9'
          - os: macos-latest
            python-version: '3.10'
            macos_target: '11.0'
    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos_target }}

    steps:
    - name: Checkout workspace
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft-workspace
        submodules: recursive
        # checkout full history to support tagged releases
        fetch-depth: 0

    - name: Pull submodule updates and checkout the latest tags if they exist
      run: |
        git submodule update --recursive --remote
        git submodule foreach 'git fetch origin; git checkout $(git describe --tags `git rev-list --tags --max-count=1`);'

    - name: Remove current repo from workspace
      run: rm -rfv ${{ github.event.repository.name }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # checkout full history for setuptools-scm
        fetch-depth: 0
        path: ${{ github.event.repository.name }}
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build sdist
      working-directory: ${{ github.event.repository.name }}
      run: |
        pip install tox
        tox -e sdist

    - name: Build wheels
      run: |
        pip install cibuildwheel>=2.8
        cibuildwheel --output-dir pkgcraft-python/wheels pkgcraft-python

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pkgcraft-python
        path: |
          pkgcraft-python/dist/
          pkgcraft-python/wheels/
        if-no-files-found: error
        retention-days: 3

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      if: ${{ matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/') }}
      with:
        files: pkgcraft-python/dist/*.tar.gz
        fail_on_unmatched_files: true

    - name: Upload sdist to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: ${{ matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/') }}
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: pkgcraft-python/dist/

    - name: Upload wheels to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: pkgcraft-python/wheels/
